# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'GAP Days Spring 2019'
tagline:          'Modern Permutation Group Algorithms'
description:      '18th to 22nd March 2019'
location:         'University of Halle'
url:              https://www.gapdays.de
baseurl:          /gapdays2019-spring


exclude: [ "LICENSE.hyde.md", "README.hyde.md", "program.aux", "program.log", "program.out", "program.tex", "misc" ]
