# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'GAP Days Spring 2019'
tagline:          'Modern Permutation Group Algorithms'
description:      '18<sup>th</sup> to 22<sup>nd</sup> March 2019'
location:         'Martin Luther University of Halle-Wittenberg'
url:              https://www.gapdays.de
baseurl:          /gapdays2019-spring


exclude: [ "LICENSE.hyde.md", "README.hyde.md", "program.aux", "program.log", "program.out", "program.tex", "misc" ]
