# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'CoDiMa Workshop 2019'
tagline:          'Algorithms and Software for Discrete Computational Mathematics'
description:      '23<sup>rd</sup> to 25<sup>th</sup> May 2019'
location:         'The University of Manchester'
url:              https://CIRCA-StAndrews.github.io
baseurl:          /codima2019workshop 


exclude: [ "LICENSE.hyde.md", "README.hyde.md", "program.aux", "program.log", "program.out", "program.tex", "misc" ]
